// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package assignment1.grpc.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
