// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package assignment1.grpc.grpc;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.grpc.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  assignment1.grpc.grpc.Greeting getGreeting();
  /**
   * <code>.grpc.Greeting greeting = 1;</code>
   */
  assignment1.grpc.grpc.GreetingOrBuilder getGreetingOrBuilder();
}
