// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package assignment1.grpc.grpc;

public interface MessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Messages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .grpc.Greeting messages = 1;</code>
   */
  java.util.List<assignment1.grpc.grpc.Greeting>
      getMessagesList();
  /**
   * <code>repeated .grpc.Greeting messages = 1;</code>
   */
  assignment1.grpc.grpc.Greeting getMessages(int index);
  /**
   * <code>repeated .grpc.Greeting messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .grpc.Greeting messages = 1;</code>
   */
  java.util.List<? extends assignment1.grpc.grpc.GreetingOrBuilder>
      getMessagesOrBuilderList();
  /**
   * <code>repeated .grpc.Greeting messages = 1;</code>
   */
  assignment1.grpc.grpc.GreetingOrBuilder getMessagesOrBuilder(
      int index);
}
