FROM openjdk:18
ARG JAR_FILE=target/DS2022_30422_Scutea_Emilia_1_Backend-1.0-SNAPSHOT.jar
COPY ${JAR_FILE} DS2022_30422_Scutea_Emilia_1_Backend-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","DS2022_30422_Scutea_Emilia_1_Backend-1.0-SNAPSHOT.jar"]